name: CI Backend

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci-backend.yml'

concurrency:
  group: ci-backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-build:
    name: backend build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Publish Test Report
        if: always()
        uses: dorny/test-reporter@v2.1.1
        with:
          name: JUnit Tests
          path: '**/build/test-results/test/TEST-*.xml'
          reporter: java-junit
          fail-on-empty: false