name: CI Frontend

on:
  pull_request:
    paths: ['frontend/**', '.github/workflows/ci-frontend.yml']
  push:
    branches: [ main ]
    paths: ['frontend/**', '.github/workflows/ci-frontend.yml']

concurrency:
  group: ci-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'                 # trzymamy Node 24
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install
        run: npm ci                                   # szybciej i deterministycznie niż 'npm i'

      - name: Lint
        run: npm run lint --if-present

      - name: Unit tests
        run: npm test || true                         # nie blokuj PR na starcie, doprecyzujemy później

      - name: Build (prod)
        run: npm run build:prod

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist/