name: CI Frontend

on:
  pull_request:
    paths: ['frontend/**', '.github/workflows/ci-frontend.yaml']
  push:
    branches: [ main ]
    paths: ['frontend/**', '.github/workflows/ci-frontend.yaml']

concurrency:
  group: ci-frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: 'frontend/.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Build and verify
        run: npm run verify